### ISSUE TITLE
TL;DR instructions produce error

### ISSUE THREAD

**Issue by pepijndevos** [bitnami/bitnami-docker-jupyterhub#2]
**Description**

The command that Docker hub tells you to run produces an error right away

**Steps to reproduce the issue:**

```
$ docker run --name jupyterhub bitnami/jupyterhub:latest
```

**Describe the results you received:**

```
[I 2021-12-06 14:57:55.621 JupyterHub app:2479] Running JupyterHub version 1.5.0
[I 2021-12-06 14:57:55.621 JupyterHub app:2510] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.5.0
[I 2021-12-06 14:57:55.621 JupyterHub app:2510] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.5.0
[I 2021-12-06 14:57:55.621 JupyterHub app:2510] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.5.0
[I 2021-12-06 14:57:55.627 JupyterHub app:1599] Writing cookie_secret to /jupyterhub_cookie_secret
[E 2021-12-06 14:57:55.627 JupyterHub app:2989]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 2986, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 2519, in initialize
        self.init_secrets()
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 1601, in init_secrets
        with open(secret_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/jupyterhub_cookie_secret'
    
```

**Describe the results you expected:**

Uh, a working JupyterHub image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        dea9396e18
 Built:             Sat Nov 20 12:57:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       847da184ad
  Built:            Sat Nov 20 12:57:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.8
  GitCommit:        1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 349
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.4GiB
 Name: archlinux
 ID: RKPR:OSJQ:NY3B:I6MV:XNK3:XKDK:O7ZI:YB7U:2S4G:F2LA:WPYU:VTOS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: pepijndevos
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Just my own laptop...

**Comment by javsalgar** [comment]
Hi,

Note that this solution is meant to be run in a Kubernetes cluster, not using docker run. Could you try running it in a Kubernetes cluster using the bitnami/jupyterhub helm chart?

**Comment by pepijndevos** [comment]
I do not run a Kubernetes cluster.

If that's the case, maybe remove the TL;DR command from the page? It obviously tells you to use `docker run`

`$ docker run --name jupyterhub bitnami/jupyterhub:latest`

**Comment by miguelaeh** [comment]
Hi @pepijndevos ,
yes, we should delete that form the README. it was aded because we use a general template
