### ISSUE TITLE
Reopen of #2 TL;DR instructions produce error

### ISSUE THREAD

**Issue by sei-amellinger** [bitnami/bitnami-docker-jupyterhub#3]
### Name and Version

bitnami/jupyterhub

### What steps will reproduce the bug?

NOTE: This is basically a repost of the Issue of #2 which was automatically closed for reasons. The docs should be updated, and it would be nice to have a the same support in a single environment

```
docker run --rm --name jupyterhub bitnami/jupyterhub:latest
```

Or what I really would like to do is that command to fire up a notebook server with -p 8081:8081.

### What is the expected behavior?

That it starts a notebook server I can connect to, especially doing something like: 

```
docker run -p 8081:8081 --rm --name jupyterhub bitnami/jupyterhub:latest notebook
```

### What do you see instead?

```
[I 2022-02-18 16:15:38.931 JupyterHub app:2479] Running JupyterHub version 1.5.0
[I 2022-02-18 16:15:38.931 JupyterHub app:2510] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.5.0
[I 2022-02-18 16:15:38.931 JupyterHub app:2510] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.5.0
[I 2022-02-18 16:15:38.931 JupyterHub app:2510] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.5.0
[I 2022-02-18 16:15:38.937 JupyterHub app:1599] Writing cookie_secret to /jupyterhub_cookie_secret
[E 2022-02-18 16:15:38.937 JupyterHub app:2989]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 2986, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 2519, in initialize
        self.init_secrets()
      File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/app.py", line 1601, in init_secrets
        with open(secret_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/jupyterhub_cookie_secret'
```

### Additional information

I am running on an Ubuntu 18.04 host and with the latest image.

I know that you intended it to be run from within Kubernetes, but I just wasted 45 minutes trying to get this working on my machine, had to google to find out I'm not the ideal use case. This was one of the top hits on Docker Hub for Jupyter.

So at a minimum please fix your docs so other folks don't waste their time. And having a bot auto-close a perfectly valid request when it is actually in the your hands is uncool.

In a perfect world, please make it work.

**Comment by miguelaeh** [comment]
We just updated the README and it will be released soon by our pipeline with the changes.
thanks for the update

**Comment by asdf93074** [comment]
@miguelaeh Any updates on this? Also, how exactly does this image differ by running on docker directly vs within kubernetes?

**Comment by miguelaeh** [comment]
> Any updates on this?

We deleted the problematic section from the readme as stated in the [comment](https://github.com/bitnami/bitnami-docker-jupyterhub/issues/3#issuecomment-1046753797).

> Also, how exactly does this image differ by running on docker directly vs within kubernetes?

Running the image manually with docker would require several manual configuration and volume mounts, as well as some other services. We recommend using our [helm chart](https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub), which already configures all that automatically.

**Comment by sei-amellinger** [comment]
Looks good to me.
